-- MySQL Script generated by MySQL Workbench
-- qua 01 mar 2023 13:28:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Data_Nascimento` DATE NULL DEFAULT NULL,
  `Idade` INT NULL DEFAULT NULL,
  `Sexo` VARCHAR(10) NULL DEFAULT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `RG` VARCHAR(15) NULL DEFAULT NULL,
  `Telefone` VARCHAR(45) NULL DEFAULT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(15) NULL DEFAULT NULL,
  `Estado` VARCHAR(100) NULL DEFAULT NULL,
  `Cidade` VARCHAR(100) NULL DEFAULT NULL,
  `Endereco` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(10) NOT NULL,
  `Data_Cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anamnese` (
  `idAnamnese` INT NOT NULL,
  `Atividade` VARCHAR(45) NULL DEFAULT NULL,
  `Tempo_Pratica` VARCHAR(45) NULL DEFAULT NULL,
  `Objetivo` VARCHAR(45) NULL DEFAULT NULL,
  `Fumante` VARCHAR(45) NULL DEFAULT NULL,
  `Alcool` VARCHAR(45) NULL DEFAULT NULL,
  `Historico_Fam` VARCHAR(100) NULL DEFAULT NULL,
  `Hipertensao` VARCHAR(45) NULL DEFAULT NULL,
  `Colesterol` VARCHAR(45) NULL DEFAULT NULL,
  `Diabetes` VARCHAR(45) NULL DEFAULT NULL,
  `Cardiaco` VARCHAR(100) NULL DEFAULT NULL,
  `Cirurgia` VARCHAR(100) NULL DEFAULT NULL,
  `Fratura` VARCHAR(100) NULL DEFAULT NULL,
  `Lesao` VARCHAR(100) NULL DEFAULT NULL,
  `Dor` VARCHAR(100) NULL DEFAULT NULL,
  `Movimentos` VARCHAR(100) NULL DEFAULT NULL,
  `Artrite` VARCHAR(100) NULL DEFAULT NULL,
  `Medicamento` VARCHAR(100) NULL DEFAULT NULL,
  `Outros` VARCHAR(100) NULL DEFAULT NULL,
  `Alimentacao` VARCHAR(200) NULL DEFAULT NULL,
  `Data_Cadastro` DATE NULL DEFAULT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAnamnese`),
  INDEX `fk_Anamnese_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Anamnese_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exercicios` (
  `idExercicios` INT NOT NULL AUTO_INCREMENT,
  `Grupo_Muscular` CHAR(3) NULL DEFAULT NULL,
  `Descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idExercicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medidas` (
  `idMedidas` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` DATE NULL DEFAULT NULL,
  `Peso` FLOAT NULL DEFAULT NULL,
  `Altura` FLOAT NULL DEFAULT NULL,
  `Freq_Card` INT NULL DEFAULT NULL,
  `Pressao_Arterial` VARCHAR(45) NULL DEFAULT NULL,
  `Torax` FLOAT NULL DEFAULT NULL,
  `Cintura` FLOAT NULL DEFAULT NULL,
  `Abdomen` FLOAT NULL DEFAULT NULL,
  `Quadril` FLOAT NULL DEFAULT NULL,
  `Braco_Direito` FLOAT NULL DEFAULT NULL,
  `Braco_Esquerdo` FLOAT NULL DEFAULT NULL,
  `Antebraco_Direito` FLOAT NULL DEFAULT NULL,
  `Antebraco_Esquerdo` FLOAT NULL DEFAULT NULL,
  `Coxa_Direita` FLOAT NULL DEFAULT NULL,
  `Coxa_Esquerda` FLOAT NULL DEFAULT NULL,
  `Panturrilha_Direita` FLOAT NULL DEFAULT NULL,
  `Panturrilha_Esquerda` FLOAT NULL DEFAULT NULL,
  `Peitoral` FLOAT NULL DEFAULT NULL,
  `AxilarMedia` FLOAT NULL DEFAULT NULL,
  `Abdominal` FLOAT NULL DEFAULT NULL,
  `SupraIliaca` FLOAT NULL DEFAULT NULL,
  `Sub_Escapular` FLOAT NULL DEFAULT NULL,
  `Tricipital` FLOAT NULL DEFAULT NULL,
  `Coxa` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idMedidas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Data_Nascimento` DATE NULL DEFAULT NULL,
  `Sexo` VARCHAR(10) NULL DEFAULT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(15) NULL DEFAULT NULL,
  `CREF` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` VARCHAR(100) NULL DEFAULT NULL,
  `Cidade` VARCHAR(100) NULL DEFAULT NULL,
  `Endereco` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Teste_VO2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teste_VO2` (
  `idTeste_VO2` INT NOT NULL AUTO_INCREMENT,
  `Data_Teste` DATE NULL DEFAULT NULL,
  `Velocidade_Inicial` INT NULL DEFAULT NULL,
  `FC_Repouso` INT NULL DEFAULT NULL,
  `Pressao_Inicio` VARCHAR(45) NULL DEFAULT NULL,
  `Pressao_Final` VARCHAR(45) NULL DEFAULT NULL,
  `FC_Teste` INT NULL DEFAULT NULL,
  `Tempo_Teste` INT NULL DEFAULT NULL,
  `Velocidade_Teste` INT NULL DEFAULT NULL,
  `Esforco_Teste` INT NULL DEFAULT NULL,
  `Resultado_VO2` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTeste_VO2`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Teste_Forca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teste_Forca` (
  `idTeste_Forca` INT NOT NULL AUTO_INCREMENT,
  `Data_Teste` DATE NULL DEFAULT NULL,
  `Carga_Inicial` INT NULL DEFAULT NULL,
  `Rep_Inicial` INT NULL DEFAULT NULL,
  `Meta_Carga` INT NULL DEFAULT NULL,
  `Meta_Rep` INT NULL DEFAULT NULL,
  `Primeira_Tentativa` INT NULL DEFAULT NULL,
  `Segunda_Tentativa` INT NULL DEFAULT NULL,
  `Terceira_Tentativa` INT NULL DEFAULT NULL,
  `Resultado_Rep` INT NULL DEFAULT NULL,
  `Resultado_Kg` INT NULL DEFAULT NULL,
  `idExercicios` INT NOT NULL,
  PRIMARY KEY (`idTeste_Forca`),
  INDEX `fk_Teste_Forca_Exercicios1_idx` (`idExercicios` ASC) VISIBLE,
  CONSTRAINT `fk_Teste_Forca_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `mydb`.`Exercicios` (`idExercicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resultado` (
  `idResultado` INT NOT NULL,
  `Peso` FLOAT NULL DEFAULT NULL,
  `IMC` FLOAT NULL DEFAULT NULL,
  `Abdomen` FLOAT NULL DEFAULT NULL,
  `RCQ` FLOAT NULL DEFAULT NULL,
  `Percent_Gord` FLOAT NULL DEFAULT NULL,
  `Massa_Gorda` FLOAT NULL DEFAULT NULL,
  `Percent_Magra` FLOAT NULL DEFAULT NULL,
  `Massa_Magra` FLOAT NULL DEFAULT NULL,
  `FC` FLOAT NULL DEFAULT NULL,
  `VO` FLOAT NULL DEFAULT NULL,
  `idTeste_VO2` INT NOT NULL,
  `idTeste_Forca` INT NOT NULL,
  `idMedidas` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idResultado`),
  INDEX `fk_Resultado_Teste_VO21_idx` (`idTeste_VO2` ASC) VISIBLE,
  INDEX `fk_Resultado_Teste_Forca1_idx` (`idTeste_Forca` ASC) VISIBLE,
  INDEX `fk_Resultado_Medidas1_idx` (`idMedidas` ASC) VISIBLE,
  INDEX `fk_Resultado_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Resultado_Teste_VO21`
    FOREIGN KEY (`idTeste_VO2`)
    REFERENCES `mydb`.`Teste_VO2` (`idTeste_VO2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Teste_Forca1`
    FOREIGN KEY (`idTeste_Forca`)
    REFERENCES `mydb`.`Teste_Forca` (`idTeste_Forca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Medidas1`
    FOREIGN KEY (`idMedidas`)
    REFERENCES `mydb`.`Medidas` (`idMedidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Series` (
  `idSeries` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(45) NULL DEFAULT NULL,
  `Fase` VARCHAR(45) NULL DEFAULT NULL,
  `Serie` VARCHAR(45) NULL DEFAULT NULL,
  `Percent_Carga` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idSeries`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treino` (
  `idTreino` INT NOT NULL AUTO_INCREMENT,
  `idSeries` INT NOT NULL,
  `idExercicios` INT NOT NULL,
  `Carga` INT NULL DEFAULT NULL,
  `Feedback` INT NULL DEFAULT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTreino`),
  INDEX `fk_Treino_Series1_idx` (`idSeries` ASC) VISIBLE,
  INDEX `fk_Treino_Exercicios1_idx` (`idExercicios` ASC) VISIBLE,
  INDEX `fk_Treino_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Treino_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `mydb`.`Exercicios` (`idExercicios`),
  CONSTRAINT `fk_Treino_Series1`
    FOREIGN KEY (`idSeries`)
    REFERENCES `mydb`.`Series` (`idSeries`),
  CONSTRAINT `fk_Treino_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
