-- MySQL Script generated by MySQL Workbench
-- qua 01 mar 2023 13:28:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `idade` INT NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(15) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anamnese` (
  `idAnamnese` INT NOT NULL,
  `atividade` VARCHAR(45) NULL DEFAULT NULL,
  `tempoPratica` VARCHAR(45) NULL DEFAULT NULL,
  `objetivo` VARCHAR(45) NULL DEFAULT NULL,
  `fumante` VARCHAR(45) NULL DEFAULT NULL,
  `alcool` VARCHAR(45) NULL DEFAULT NULL,
  `historicoFam` VARCHAR(100) NULL DEFAULT NULL,
  `hipertensao` VARCHAR(45) NULL DEFAULT NULL,
  `colesterol` VARCHAR(45) NULL DEFAULT NULL,
  `diabetes` VARCHAR(45) NULL DEFAULT NULL,
  `cardiaco` VARCHAR(100) NULL DEFAULT NULL,
  `cirurgia` VARCHAR(100) NULL DEFAULT NULL,
  `fratura` VARCHAR(100) NULL DEFAULT NULL,
  `lesao` VARCHAR(100) NULL DEFAULT NULL,
  `dor` VARCHAR(100) NULL DEFAULT NULL,
  `movimentos` VARCHAR(100) NULL DEFAULT NULL,
  `artrite` VARCHAR(100) NULL DEFAULT NULL,
  `medicamento` VARCHAR(100) NULL DEFAULT NULL,
  `outros` VARCHAR(100) NULL DEFAULT NULL,
  `alimentacao` VARCHAR(200) NULL DEFAULT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAnamnese`),
  INDEX `fk_Anamnese_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Anamnese_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercicios` (
  `idExercicios` INT NOT NULL AUTO_INCREMENT,
  `grupoMuscular` CHAR(3) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idExercicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medidas` (
  `idMedidas` INT NOT NULL AUTO_INCREMENT,
  `dataCadastro` DATE NULL DEFAULT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `altura` FLOAT NULL DEFAULT NULL,
  `freqCard` INT NULL DEFAULT NULL,
  `pressaoArterial` VARCHAR(45) NULL DEFAULT NULL,
  `torax` FLOAT NULL DEFAULT NULL,
  `cintura` FLOAT NULL DEFAULT NULL,
  `abdomen` FLOAT NULL DEFAULT NULL,
  `quadril` FLOAT NULL DEFAULT NULL,
  `bracoDireito` FLOAT NULL DEFAULT NULL,
  `bracoEsquerdo` FLOAT NULL DEFAULT NULL,
  `antebracoDireito` FLOAT NULL DEFAULT NULL,
  `antebracoEsquerdo` FLOAT NULL DEFAULT NULL,
  `coxaDireita` FLOAT NULL DEFAULT NULL,
  `coxaEsquerda` FLOAT NULL DEFAULT NULL,
  `panturrilhaDireita` FLOAT NULL DEFAULT NULL,
  `panturrilhaEsquerda` FLOAT NULL DEFAULT NULL,
  `peitoral` FLOAT NULL DEFAULT NULL,
  `axilarMedia` FLOAT NULL DEFAULT NULL,
  `abdominal` FLOAT NULL DEFAULT NULL,
  `supraIliaca` FLOAT NULL DEFAULT NULL,
  `subEscapular` FLOAT NULL DEFAULT NULL,
  `tricipital` FLOAT NULL DEFAULT NULL,
  `coxa` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idMedidas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `cref` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`testeVO2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`testeVO2` (
  `idTesteVO2` INT NOT NULL AUTO_INCREMENT,
  `dataTeste` DATE NULL DEFAULT NULL,
  `velocidadeInicial` INT NULL DEFAULT NULL,
  `fcRepouso` INT NULL DEFAULT NULL,
  `pressaoInicio` VARCHAR(45) NULL DEFAULT NULL,
  `pressaoFinal` VARCHAR(45) NULL DEFAULT NULL,
  `fcTeste` INT NULL DEFAULT NULL,
  `tempoTeste` INT NULL DEFAULT NULL,
  `velocidadeTeste` INT NULL DEFAULT NULL,
  `esforcoTeste` INT NULL DEFAULT NULL,
  `resultadoVO2` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTesteVO2`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`testeForca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`testeForca` (
  `idTesteForca` INT NOT NULL AUTO_INCREMENT,
  `dataTeste` DATE NULL DEFAULT NULL,
  `cargaInicial` INT NULL DEFAULT NULL,
  `repInicial` INT NULL DEFAULT NULL,
  `metaCarga` INT NULL DEFAULT NULL,
  `metaRep` INT NULL DEFAULT NULL,
  `primeiraTentativa` INT NULL DEFAULT NULL,
  `segundaTentativa` INT NULL DEFAULT NULL,
  `terceiraTentativa` INT NULL DEFAULT NULL,
  `resultadoRep` INT NULL DEFAULT NULL,
  `resultadoKg` INT NULL DEFAULT NULL,
  `idExercicios` INT NOT NULL,
  PRIMARY KEY (`idTesteForca`),
  INDEX `fk_TesteForca_Exercicios1_idx` (`idExercicios` ASC),
  CONSTRAINT `fk_TesteForca_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `mydb`.`exercicios` (`idExercicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resultado` (
  `idResultado` INT NOT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `imc` FLOAT NULL DEFAULT NULL,
  `abdomen` FLOAT NULL DEFAULT NULL,
  `rcq` FLOAT NULL DEFAULT NULL,
  `percentGord` FLOAT NULL DEFAULT NULL,
  `massaGorda` FLOAT NULL DEFAULT NULL,
  `percentMagra` FLOAT NULL DEFAULT NULL,
  `massaMagra` FLOAT NULL DEFAULT NULL,
  `fc` FLOAT NULL DEFAULT NULL,
  `vo` FLOAT NULL DEFAULT NULL,
  `idTesteVO2` INT NOT NULL,
  `idTesteForca` INT NOT NULL,
  `idMedidas` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idResultado`),
  INDEX `fk_Resultado_TesteVO21_idx` (`idTesteVO2` ASC),
  INDEX `fk_Resultado_TesteForca1_idx` (`idTesteForca` ASC),
  INDEX `fk_Resultado_Medidas1_idx` (`idMedidas` ASC),
  INDEX `fk_Resultado_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Resultado_TesteVO21`
    FOREIGN KEY (`idTesteVO2`)
    REFERENCES `mydb`.`testeVO2` (`idTesteVO2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_TesteForca1`
    FOREIGN KEY (`idTesteForca`)
    REFERENCES `mydb`.`testeForca` (`idTesteForca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Medidas1`
    FOREIGN KEY (`idMedidas`)
    REFERENCES `mydb`.`medidas` (`idMedidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`series` (
  `idSeries` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NULL DEFAULT NULL,
  `fase` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `percentCarga` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idSeries`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino` (
  `idTreino` INT NOT NULL AUTO_INCREMENT,
  `idSeries` INT NOT NULL,
  `idExercicios` INT NOT NULL,
  `carga` INT NULL DEFAULT NULL,
  `feedback` INT NULL DEFAULT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTreino`),
  INDEX `fk_Treino_Series1_idx` (`idSeries` ASC),
  INDEX `fk_Treino_Exercicios1_idx` (`idExercicios` ASC),
  INDEX `fk_Treino_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Treino_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `mydb`.`exercicios` (`idExercicios`),
  CONSTRAINT `fk_Treino_Series1`
    FOREIGN KEY (`idSeries`)
    REFERENCES `mydb`.`series` (`idSeries`),
  CONSTRAINT `fk_Treino_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
