-- MySQL Script generated by MySQL Workbench
-- qua 30 nov 2022 10:08:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Data_Nascimento` DATE NULL,
  `Sexo` VARCHAR(10) NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `RG` VARCHAR(15) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(15) NULL,
  `Estado` VARCHAR(100) NULL,
  `Cidade` VARCHAR(100) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(10) NOT NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Circunferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Circunferencias` (
  `idCircunferencias` INT NOT NULL AUTO_INCREMENT,
  `Torax` FLOAT NULL,
  `Cintura` FLOAT NULL,
  `Abdomen` FLOAT NULL,
  `Quadril` FLOAT NULL,
  `Braco_Direito` FLOAT NULL,
  `Braco_Esquerdo` FLOAT NULL,
  `Antebraco_Direito` FLOAT NULL,
  `Antebraco_Esquerdo` FLOAT NULL,
  `Coxa_Direita` FLOAT NULL,
  `Coxa_Esquerda` FLOAT NULL,
  `Panturrilha_Direita` FLOAT NULL,
  `Panturrilha_Esquerda` FLOAT NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idCircunferencias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exercicios` (
  `idExercicios` INT NOT NULL AUTO_INCREMENT,
  `Grupo_Muscular` CHAR(3) NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idExercicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Series` (
  `idSeries` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(45) NULL,
  `Fase` VARCHAR(45) NULL,
  `Serie` VARCHAR(45) NULL,
  `Percent_Carga` VARCHAR(5) NULL,
  PRIMARY KEY (`idSeries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Data_Nascimento` DATE NULL,
  `Sexo` VARCHAR(10) NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(15) NULL,
  `CREF` VARCHAR(45) NULL,
  `Estado` VARCHAR(100) NULL,
  `Cidade` VARCHAR(100) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treino` (
  `idTreino` INT NOT NULL AUTO_INCREMENT,
  `idSeries` INT NOT NULL,
  `idExercicios` INT NOT NULL,
  `Carga` INT NULL,
  `Feedback` INT NULL,
  `idUsuario` INT NOT NULL,,
  PRIMARY KEY (`idTreino`),
  INDEX `fk_Treino_Series1_idx` (`idSeries` ASC),
  INDEX `fk_Treino_Exercicios1_idx` (`idExercicios` ASC),
  INDEX `fk_Treino_Usuario1_idx` (`idUsuario` ASC),,
  CONSTRAINT `fk_Treino_Series1`
    FOREIGN KEY (`idSeries`)
    REFERENCES `mydb`.`Series` (`idSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treino_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `mydb`.`Exercicios` (`idExercicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treino_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dobras_Cutaneas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dobras_Cutaneas` (
  `idDobras_Cutaneas` INT NOT NULL AUTO_INCREMENT,
  `Peitoral` FLOAT NULL,
  `AxilarMedia` FLOAT NULL,
  `Abdominal` FLOAT NULL,
  `SupraIliaca` FLOAT NULL,
  `Sub_Escapular` FLOAT NULL,
  `Tricipital` FLOAT NULL,
  `Coxa` FLOAT NULL,
  `Somatorio` FLOAT NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idDobras_Cutaneas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teste_Forca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teste_Forca` (
  `idTeste_Forca` INT NOT NULL AUTO_INCREMENT,
  `Data_Teste` DATE NULL,
  `Exercicio` VARCHAR(45) NULL,
  `Carga_Inicial` INT NULL,
  `Rep_Inicial` INT NULL,
  `Meta_Carga` INT NULL,
  `Meta_Rep` INT NULL,
  `Primeira_Tentativa` INT NULL,
  `Segunda_Tentativa` INT NULL,
  `Terceira_Tentativa` INT NULL,
  `Resultado_Rep` INT NULL,
  `Resultado_Kg` INT NULL,
  `idExercicios` INT NOT NULL,
  PRIMARY KEY (`idTeste_Forca`),
  INDEX `fk_Teste_Forca_Exercicios1_idx` (`idExercicios` ASC),
  CONSTRAINT `fk_Teste_Forca_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `mydb`.`Exercicios` (`idExercicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teste_VO2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teste_VO2` (
  `idTeste_VO2` INT NOT NULL AUTO_INCREMENT,
  `Data_Teste` DATE NULL,
  `Velocidade_Inicial` INT NULL,
  `FC_Repouso` INT NULL,
  `Pressao_Inicio` VARCHAR(45) NULL,
  `Pressao_Final` VARCHAR(45) NULL,
  `FC_Teste` INT NULL,
  `Tempo_Teste` INT NULL,
  `Velocidade_Teste` INT NULL,
  `Esforco_Teste` INT NULL,
  `Resultado_VO2` INT NULL,
  PRIMARY KEY (`idTeste_VO2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dados_Iniciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dados_Iniciais` (
  `idDados_Iniciais` INT NOT NULL AUTO_INCREMENT,
  `Peso` FLOAT NULL,
  `Altura` FLOAT NULL,
  `Freq_Card` INT NULL,
  `Pressao_Arterial` VARCHAR(45) NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idDados_Iniciais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resultado` (
  `idResultado` INT NOT NULL,
  `Peso` FLOAT NULL,
  `IMC` FLOAT NULL,
  `Abdomen` FLOAT NULL,
  `RCQ` FLOAT NULL,
  `Percent_Gord` FLOAT NULL,
  `Massa_Gorda` FLOAT NULL,
  `Percent_Magra` FLOAT NULL,
  `Massa_Magra` FLOAT NULL,
  `FC` FLOAT NULL,
  `VO` FLOAT NULL,
  PRIMARY KEY (`idResultado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anamnese` (
  `idAnamnese` INT NOT NULL,
  `Atividade` VARCHAR(45) NULL,
  `Tempo_Pratica` VARCHAR(45) NULL,
  `Objetivo` VARCHAR(45) NULL,
  `Fumante` VARCHAR(45) NULL,
  `Alcool` VARCHAR(45) NULL,
  `Historico_Fam` VARCHAR(100) NULL,
  `Hipertensao` VARCHAR(45) NULL,
  `Colesterol` VARCHAR(45) NULL,
  `Diabetes` VARCHAR(45) NULL,
  `Cardiaco` VARCHAR(100) NULL,
  `Cirurgia` VARCHAR(100) NULL,
  `Fratura` VARCHAR(100) NULL,
  `Lesao` VARCHAR(100) NULL,
  `Dor` VARCHAR(100) NULL,
  `Movimentos` VARCHAR(100) NULL,
  `Artrite` VARCHAR(100) NULL,
  `Medicamento` VARCHAR(100) NULL,
  `Outros` VARCHAR(100) NULL,
  `Alimentacao` VARCHAR(200) NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idAnamnese`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao_Fisica` (
  `idAvaliacao_Fisica` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idAnamnese` INT NOT NULL,
  `idDados_Iniciais` INT NOT NULL,
  `idCircunferencias` INT NOT NULL,
  `idDobras_Cutaneas` INT NOT NULL,
  `idTeste_VO2` INT NOT NULL,
  `idTeste_Forca` INT NOT NULL,
  `idResultado` INT NOT NULL,
  `idProfessor` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao_Fisica`),
  INDEX `fk_Avaliacao_Fisica_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Avaliacao_Fisica_Dados_Iniciais1_idx` (`idDados_Iniciais` ASC),
  INDEX `fk_Avaliacao_Fisica_Circunferencias1_idx` (`idCircunferencias` ASC),
  INDEX `fk_Avaliacao_Fisica_Dobras_Cutaneas1_idx` (`idDobras_Cutaneas` ASC),
  INDEX `fk_Avaliacao_Fisica_Teste_VO21_idx` (`idTeste_VO2` ASC),
  INDEX `fk_Avaliacao_Fisica_Teste_Forca1_idx` (`idTeste_Forca` ASC),
  INDEX `fk_Avaliacao_Fisica_Resultado1_idx` (`idResultado` ASC),
  INDEX `fk_Avaliacao_Fisica_Anamnese1_idx` (`idAnamnese` ASC),
  INDEX `fk_Avaliacao_Fisica_Professor1_idx` (`idProfessor` ASC),
  CONSTRAINT `fk_Avaliacao_Fisica_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Dados_Iniciais1`
    FOREIGN KEY (`idDados_Iniciais`)
    REFERENCES `mydb`.`Dados_Iniciais` (`idDados_Iniciais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Circunferencias1`
    FOREIGN KEY (`idCircunferencias`)
    REFERENCES `mydb`.`Circunferencias` (`idCircunferencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Dobras_Cutaneas1`
    FOREIGN KEY (`idDobras_Cutaneas`)
    REFERENCES `mydb`.`Dobras_Cutaneas` (`idDobras_Cutaneas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Teste_VO21`
    FOREIGN KEY (`idTeste_VO2`)
    REFERENCES `mydb`.`Teste_VO2` (`idTeste_VO2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Teste_Forca1`
    FOREIGN KEY (`idTeste_Forca`)
    REFERENCES `mydb`.`Teste_Forca` (`idTeste_Forca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Resultado1`
    FOREIGN KEY (`idResultado`)
    REFERENCES `mydb`.`Resultado` (`idResultado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Anamnese1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `mydb`.`Anamnese` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Professor1`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
