-- MySQL Script generated by MySQL Workbench
-- seg 06 mar 2023 14:58:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `idade` INT NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(15) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anamnese` (
  `idAnamnese` INT NOT NULL,
  `atividade` VARCHAR(45) NULL DEFAULT NULL,
  `objetivo` VARCHAR(45) NULL DEFAULT NULL,
  `fumante` VARCHAR(45) NULL DEFAULT NULL,
  `alcool` VARCHAR(45) NULL DEFAULT NULL,
  `historicoFam` VARCHAR(100) NULL DEFAULT NULL,
  `hipertensao` VARCHAR(45) NULL DEFAULT NULL,
  `colesterol` VARCHAR(45) NULL DEFAULT NULL,
  `diabetes` VARCHAR(45) NULL DEFAULT NULL,
  `cardiaco` VARCHAR(100) NULL DEFAULT NULL,
  `cirurgia` VARCHAR(100) NULL DEFAULT NULL,
  `fratura` VARCHAR(100) NULL DEFAULT NULL,
  `lesao` VARCHAR(100) NULL DEFAULT NULL,
  `dor` VARCHAR(100) NULL DEFAULT NULL,
  `movimentos` VARCHAR(100) NULL DEFAULT NULL,
  `artrite` VARCHAR(100) NULL DEFAULT NULL,
  `medicamento` VARCHAR(100) NULL DEFAULT NULL,
  `outros` VARCHAR(100) NULL DEFAULT NULL,
  `alimentacao` VARCHAR(200) NULL DEFAULT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  `idAluno` INT NOT NULL,
  PRIMARY KEY (`idAnamnese`),
  INDEX `fk_anamnese_alunos1_idx` (`idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_anamnese_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`alunos` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercicios` (
  `idExercicio` INT NOT NULL AUTO_INCREMENT,
  `grupoMuscular` CHAR(3) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idExercicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medidas` (
  `idMedidas` INT NOT NULL AUTO_INCREMENT,
  `dataCadastro` DATE NULL DEFAULT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `altura` FLOAT NULL DEFAULT NULL,
  `freqCard` INT NULL DEFAULT NULL,
  `pressaoArterial` VARCHAR(45) NULL DEFAULT NULL,
  `torax` FLOAT NULL DEFAULT NULL,
  `cintura` FLOAT NULL DEFAULT NULL,
  `abdomen` FLOAT NULL DEFAULT NULL,
  `quadril` FLOAT NULL DEFAULT NULL,
  `bracoDireito` FLOAT NULL DEFAULT NULL,
  `bracoEsquerdo` FLOAT NULL DEFAULT NULL,
  `antebracoDireito` FLOAT NULL DEFAULT NULL,
  `antebracoEsquerdo` FLOAT NULL DEFAULT NULL,
  `coxaDireita` FLOAT NULL DEFAULT NULL,
  `coxaEsquerda` FLOAT NULL DEFAULT NULL,
  `panturrilhaDireita` FLOAT NULL DEFAULT NULL,
  `panturrilhaEsquerda` FLOAT NULL DEFAULT NULL,
  `peitoral` FLOAT NULL DEFAULT NULL,
  `axilarMedia` FLOAT NULL DEFAULT NULL,
  `abdominal` FLOAT NULL DEFAULT NULL,
  `supraIliaca` FLOAT NULL DEFAULT NULL,
  `subEscapular` FLOAT NULL DEFAULT NULL,
  `tricipital` FLOAT NULL DEFAULT NULL,
  `coxa` FLOAT NULL DEFAULT NULL,
  `imc` FLOAT NULL,
  `rcq` FLOAT NULL,
  `percentGord` FLOAT NULL,
  `massaGorda` FLOAT NULL,
  `massaMagra` FLOAT NULL,
  `idAluno` INT NOT NULL,
  PRIMARY KEY (`idMedidas`),
  INDEX `fk_medidas_alunos_idx` (`idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_medidas_alunos`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`alunos` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `cref` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`series` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NULL DEFAULT NULL,
  `fase` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `percentCarga` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`testeForca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`testeForca` (
  `idTesteForca` INT NOT NULL AUTO_INCREMENT,
  `dataTeste` DATE NULL DEFAULT NULL,
  `cargaInicial` INT NULL DEFAULT NULL,
  `cargaFinal` INT NULL DEFAULT NULL,
  `idAluno` INT NOT NULL,
  `idExercicio` INT NOT NULL,
  PRIMARY KEY (`idTesteForca`),
  INDEX `fk_testeForca_alunos1_idx` (`idAluno` ASC) VISIBLE,
  INDEX `fk_testeForca_exercicios1_idx` (`idExercicio` ASC) VISIBLE,
  CONSTRAINT `fk_testeForca_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`alunos` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_testeForca_exercicios1`
    FOREIGN KEY (`idExercicio`)
    REFERENCES `mydb`.`exercicios` (`idExercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`testeVO2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`testeVO2` (
  `idTesteVO2` INT NOT NULL AUTO_INCREMENT,
  `dataTeste` DATE NULL DEFAULT NULL,
  `velocidadeInicial` INT NULL DEFAULT NULL,
  `velocidadeFinal` INT NULL DEFAULT NULL,
  `fcInicial` VARCHAR(45) NULL DEFAULT NULL,
  `fcFinal` VARCHAR(45) NULL DEFAULT NULL,
  `tempoTeste` INT NULL DEFAULT NULL,
  `esforcoTeste` INT NULL DEFAULT NULL,
  `resultadoVO2` INT NULL DEFAULT NULL,
  `idAluno` INT NOT NULL,
  PRIMARY KEY (`idTesteVO2`),
  INDEX `fk_testeVO2_alunos1_idx` (`idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_testeVO2_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`alunos` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino` (
  `idTreino` INT NOT NULL AUTO_INCREMENT,
  `carga` INT NULL DEFAULT NULL,
  `feedback` INT NULL DEFAULT NULL,
  `idAluno` INT NOT NULL,
  `idExercicio` INT NOT NULL,
  `idSerie` INT NOT NULL,
  PRIMARY KEY (`idTreino`),
  INDEX `fk_treino_alunos1_idx` (`idAluno` ASC) VISIBLE,
  INDEX `fk_treino_exercicios1_idx` (`idExercicio` ASC) VISIBLE,
  INDEX `fk_treino_series1_idx` (`idSerie` ASC) VISIBLE,
  CONSTRAINT `fk_treino_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`alunos` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treino_exercicios1`
    FOREIGN KEY (`idExercicio`)
    REFERENCES `mydb`.`exercicios` (`idExercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treino_series1`
    FOREIGN KEY (`idSerie`)
    REFERENCES `mydb`.`series` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
