-- MySQL Script generated by MySQL Workbench
-- ter 15 nov 2022 21:16:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_superfit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_superfit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_superfit` DEFAULT CHARACTER SET utf8 ;
USE `db_superfit` ;

-- -----------------------------------------------------
-- Table `db_superfit`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Data_Nascimento` DATE NULL,
  `Sexo` VARCHAR(10) NULL,
  `CPF` INT NOT NULL,
  `RG` INT NULL,
  `CREF` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `CEP` INT NULL,
  `Estado` VARCHAR(100) NULL,
  `Cidade` VARCHAR(100) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` INT NOT NULL,
  `Data_Cadastro` DATE NULL,
  `Tipo` VARCHAR(15) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Circunferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Circunferencias` (
  `idCircunferencias` INT NOT NULL AUTO_INCREMENT,
  `Torax` FLOAT NULL,
  `Cintura` FLOAT NULL,
  `Abdomen` FLOAT NULL,
  `Quadril` FLOAT NULL,
  `Braco_Direito` FLOAT NULL,
  `Braco_Esquerdo` FLOAT NULL,
  `Antebraco_Direito` FLOAT NULL,
  `Antebraco_Esquerdo` FLOAT NULL,
  `Coxa_Direita` FLOAT NULL,
  `Coxa_Esquerda` FLOAT NULL,
  `Panturrilha_Direita` FLOAT NULL,
  `Panturrilha_Esquerda` FLOAT NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idCircunferencias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Exercicios_Musc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Exercicios_Musc` (
  `idExercicios_Musc` INT NOT NULL,
  `Grupo_Muscular` CHAR(3) NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idExercicios_Musc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Dados_Iniciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Dados_Iniciais` (
  `idDados_Iniciais` INT NOT NULL AUTO_INCREMENT,
  `Peso` FLOAT NULL,
  `Altura` FLOAT NULL,
  `Freq_Card` INT NULL,
  `Pressao_Arterial` VARCHAR(45) NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idDados_Iniciais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Dobras_Cutaneas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Dobras_Cutaneas` (
  `idDobras_Cutaneas` INT NOT NULL AUTO_INCREMENT,
  `Peitoral` FLOAT NULL,
  `AxilarMedia` FLOAT NULL,
  `Abdominal` FLOAT NULL,
  `SupraIliaca` FLOAT NULL,
  `Sub_Escapular` FLOAT NULL,
  `Tricipital` FLOAT NULL,
  `Coxa` FLOAT NULL,
  `Data_Cadastro` DATE NULL,
  PRIMARY KEY (`idDobras_Cutaneas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Teste_VO2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Teste_VO2` (
  `idTeste_VO2` INT NOT NULL AUTO_INCREMENT,
  `Data_Teste` DATE NULL,
  `Velocidade_Inicial` INT NULL,
  `FC_Repouso` INT NULL,
  `Pressao_Inicio` VARCHAR(45) NULL,
  `Pressao_Final` VARCHAR(45) NULL,
  `FC_Teste` INT NULL,
  `Tempo_Teste` INT NULL,
  `Velocidade_Teste` INT NULL,
  `Esforco_Teste` INT NULL,
  `Resultado_VO2` INT NULL,
  PRIMARY KEY (`idTeste_VO2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Teste_Forca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Teste_Forca` (
  `idTeste_Forca` INT NOT NULL AUTO_INCREMENT,
  `Data_Teste` DATE NULL,
  `Exercicio` VARCHAR(45) NULL,
  `Carga_Inicial` INT NULL,
  `Rep_Inicial` INT NULL,
  `Meta_Carga` INT NULL,
  `Meta_Rep` INT NULL,
  `Primeira_Tentativa` INT NULL,
  `Segunda_Tentativa` INT NULL,
  `Terceira_Tentativa` INT NULL,
  `Resultado_Rep` INT NULL,
  `Resultado_Kg` INT NULL,
  `idExercicios` INT NOT NULL,
  PRIMARY KEY (`idTeste_Forca`),
  INDEX `fk_Teste_Forca_Exercicios1_idx` (`idExercicios` ASC) VISIBLE,
  CONSTRAINT `fk_Teste_Forca_Exercicios1`
    FOREIGN KEY (`idExercicios`)
    REFERENCES `db_superfit`.`Exercicios_Musc` (`idExercicios_Musc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Resultado` (
  `idResultado` INT NOT NULL,
  `IMC` FLOAT NULL,
  `Percent_Gord` FLOAT NULL,
  `Massa_Gorda` FLOAT NULL,
  `Percent_Magra` FLOAT NULL,
  `Massa_Magra` FLOAT NULL,
  PRIMARY KEY (`idResultado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Anamnese` (
  `idAnamnese` INT NOT NULL,
  `Atividade` VARCHAR(45) NULL,
  `Tempo_Pratica` VARCHAR(45) NULL,
  `Objetivo` VARCHAR(45) NULL,
  `Fumante` VARCHAR(45) NULL,
  `Alcool` VARCHAR(45) NULL,
  `Historico_Fam` VARCHAR(100) NULL,
  `Hipertensão` VARCHAR(45) NULL,
  `Colesterol` VARCHAR(45) NULL,
  `Diabetes` VARCHAR(45) NULL,
  `Cardiaco` VARCHAR(100) NULL,
  `Cirurgia` VARCHAR(100) NULL,
  `Fratura` VARCHAR(100) NULL,
  `Lesao` VARCHAR(100) NULL,
  `Dor` VARCHAR(100) NULL,
  `Movimentos` VARCHAR(100) NULL,
  `Artrite` VARCHAR(100) NULL,
  `Medicamento` VARCHAR(100) NULL,
  `Outros` VARCHAR(100) NULL,
  `Alimentacao` VARCHAR(200) NULL,
  PRIMARY KEY (`idAnamnese`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Avaliacao_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Avaliacao_Fisica` (
  `idAvaliacao_Fisica` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idAnamnese` INT NOT NULL,
  `idDados_Iniciais` INT NOT NULL,
  `idCircunferencias` INT NOT NULL,
  `idDobras_Cutaneas` INT NOT NULL,
  `idTeste_VO2` INT NOT NULL,
  `idTeste_Forca` INT NOT NULL,
  `idResultado` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao_Fisica`),
  INDEX `fk_Avaliacao_Fisica_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Dados_Iniciais1_idx` (`idDados_Iniciais` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Circunferencias1_idx` (`idCircunferencias` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Dobras_Cutaneas1_idx` (`idDobras_Cutaneas` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Teste_VO21_idx` (`idTeste_VO2` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Teste_Forca1_idx` (`idTeste_Forca` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Resultado1_idx` (`idResultado` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Fisica_Anamnese1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Fisica_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_superfit`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Dados_Iniciais1`
    FOREIGN KEY (`idDados_Iniciais`)
    REFERENCES `db_superfit`.`Dados_Iniciais` (`idDados_Iniciais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Circunferencias1`
    FOREIGN KEY (`idCircunferencias`)
    REFERENCES `db_superfit`.`Circunferencias` (`idCircunferencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Dobras_Cutaneas1`
    FOREIGN KEY (`idDobras_Cutaneas`)
    REFERENCES `db_superfit`.`Dobras_Cutaneas` (`idDobras_Cutaneas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Teste_VO21`
    FOREIGN KEY (`idTeste_VO2`)
    REFERENCES `db_superfit`.`Teste_VO2` (`idTeste_VO2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Teste_Forca1`
    FOREIGN KEY (`idTeste_Forca`)
    REFERENCES `db_superfit`.`Teste_Forca` (`idTeste_Forca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Resultado1`
    FOREIGN KEY (`idResultado`)
    REFERENCES `db_superfit`.`Resultado` (`idResultado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Fisica_Anamnese1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `db_superfit`.`Anamnese` (`idAnamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Treino` (
  `idTreino` INT NOT NULL,
  `Data_Treino` DATE NULL,
  `Frequencia` INT NULL,
  `Duracao` INT NULL,
  `Carga` INT NULL,
  `Feedback` INT NULL,
  `idUsuario` INT NOT NULL,
  `idAvaliacao_Fisica` INT NOT NULL,
  PRIMARY KEY (`idTreino`),
  INDEX `fk_Treino_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Treino_Avaliacao_Fisica1_idx` (`idAvaliacao_Fisica` ASC) VISIBLE,
  CONSTRAINT `fk_Treino_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_superfit`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treino_Avaliacao_Fisica1`
    FOREIGN KEY (`idAvaliacao_Fisica`)
    REFERENCES `db_superfit`.`Avaliacao_Fisica` (`idAvaliacao_Fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Exercicios_Aero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Exercicios_Aero` (
  `idExercicios_Aero` INT NOT NULL,
  `Sigla` CHAR(3) NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idExercicios_Aero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Exercicios_Musc_Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Exercicios_Musc_Treino` (
  `idExercicios_Musc` INT NOT NULL,
  `Treino_idTreino` INT NOT NULL,
  PRIMARY KEY (`idExercicios_Musc`, `Treino_idTreino`),
  INDEX `fk_Exercicios_Musc_has_Treino_Treino1_idx` (`Treino_idTreino` ASC) VISIBLE,
  INDEX `fk_Exercicios_Musc_has_Treino_Exercicios_Musc1_idx` (`idExercicios_Musc` ASC) VISIBLE,
  CONSTRAINT `fk_Exercicios_Musc_has_Treino_Exercicios_Musc1`
    FOREIGN KEY (`idExercicios_Musc`)
    REFERENCES `db_superfit`.`Exercicios_Musc` (`idExercicios_Musc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exercicios_Musc_has_Treino_Treino1`
    FOREIGN KEY (`Treino_idTreino`)
    REFERENCES `db_superfit`.`Treino` (`idTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Exercicios_Aero_Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Exercicios_Aero_Treino` (
  `idExercicios_Aero` INT NOT NULL,
  `idTreino` INT NOT NULL,
  PRIMARY KEY (`idExercicios_Aero`, `idTreino`),
  INDEX `fk_Exercicios_Aero_has_Treino_Treino1_idx` (`idTreino` ASC) VISIBLE,
  INDEX `fk_Exercicios_Aero_has_Treino_Exercicios_Aero1_idx` (`idExercicios_Aero` ASC) VISIBLE,
  CONSTRAINT `fk_Exercicios_Aero_has_Treino_Exercicios_Aero1`
    FOREIGN KEY (`idExercicios_Aero`)
    REFERENCES `db_superfit`.`Exercicios_Aero` (`idExercicios_Aero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exercicios_Aero_has_Treino_Treino1`
    FOREIGN KEY (`idTreino`)
    REFERENCES `db_superfit`.`Treino` (`idTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Series` (
  `idSeries` INT NOT NULL,
  `Nivel` VARCHAR(45) NULL,
  `Fase` VARCHAR(45) NULL,
  `Serie` VARCHAR(45) NULL,
  `Percent_Carga` VARCHAR(5) NULL,
  PRIMARY KEY (`idSeries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_superfit`.`Series_Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_superfit`.`Series_Treino` (
  `idSeries` INT NOT NULL,
  `idTreino` INT NOT NULL,
  PRIMARY KEY (`idSeries`, `idTreino`),
  INDEX `fk_Series_has_Treino_Treino1_idx` (`idTreino` ASC) VISIBLE,
  INDEX `fk_Series_has_Treino_Series1_idx` (`idSeries` ASC) VISIBLE,
  CONSTRAINT `fk_Series_has_Treino_Series1`
    FOREIGN KEY (`idSeries`)
    REFERENCES `db_superfit`.`Series` (`idSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Series_has_Treino_Treino1`
    FOREIGN KEY (`idTreino`)
    REFERENCES `db_superfit`.`Treino` (`idTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
